from stepping_gates.gates.nand_gate import NAND
from stepping_gates.gates.not_gate import NOT
from stepping_gates.gates.and_gate import AND
from stepping_gates.gates.or_gate import OR
from stepping_gates.gates.xor_gate import XOR
from stepping_gates.gates.xax_gate import XAX
from stepping_gates.gates.increment import Incr
from stepping_gates.gates.decrement import Decr
from stepping_gates.gates.shift_left import Shiftleft
from stepping_gates.gates.parity import Parity
from stepping_gates.gates.multiplexer import Multiplexer